Initialized strapi cms with external media library and database
koiosonline/koios.world--leg pull request #10
Opened 2023-02-18 19:43 UTC by LALauw

2023-02-20 19:15 UTC, CharowDEV commented
You have to merge main before opening a PR :) so it will indicate the merge conflicts in time

2023-02-20 19:20 UTC, CharowDEV requested changes
You have to merge main before opening a PR :) so it will indicate the merge conflicts in time

2023-02-21 10:34 UTC, LALauw commented
> You have to merge main before opening a PR :) so it will indicate the merge conflicts in time

I opened this pr before you merged your pr, so that's why the conflicts occured. When I made the PR there were no merge conflicts.

2023-03-07 19:07 UTC, CharowDEV approved these changes

2023-03-07 19:07 UTC, merged